version: '2.2'
services:
  gpg:
    image: vladgh/gpg
    volumes:
      - $PWD:/app
    working_dir: /app
  encrypt-env:
    extends: gpg
    command:
      - --batch
      - --yes
      - --passphrase=$ENV_PASSWORD
      - --output=env.yaml.gpg
      - --symmetric
      - env.yaml
  decrypt-env:
    extends: gpg
    command:
      - '--decrypt'
      - '--batch'
      - "--passphrase=$ENV_PASSWORD"
      - '--output=env.yaml'
      - env.yaml.gpg
