version: '2.2'
services:
  gpg:
    image: vladgh/gpg
    volumes:
      - $PWD:/app
    working_dir: /app
  encrypt-env:
    extends: gpg
    command:
      - --batch
      - --yes
      - --passphrase=$ENV_PASSWORD
      - --output=env.gpg
      - --symmetric
      - .env
  decrypt-env:
    extends: gpg
    command:
      - '--decrypt'
      - '--batch'
      - "--passphrase=$ENV_PASSWORD"
      - '--output=.env'
      - env.gpg
  resume-make:
    build:
      context: .
      dockerfile: ./.docker/resume.dockerfile
    env_file: .env
    environment:
      GITHUB_URL: https://github.com/carlosonunez/resume
    command: make
    container_name: resume-make
    image: resume-make
    user: root
    volumes:
      - .:/home/app/resume:delegated
      - ./scripts:/scripts:ro,delegated
  terraform:
    image: hashicorp/terraform:0.12.18
    environment:
      - BUCKET
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - TF_CLI_ARGS_plan="-input=false"
      - TF_CLI_ARGS_apply="-auto-approve"
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint: 
      - sh
      - ./scripts/execute_terraform.sh
  plan:
    extends: terraform
    command: plan
  apply:
    extends: terraform
    command: apply
